package com.abc.edu.cn.community.entity;

import com.alibaba.fastjson.annotation.JSONField;
import com.baomidou.mybatisplus.activerecord.Model;
import com.baomidou.mybatisplus.annotations.TableName;

import java.io.Serializable;
import java.util.Date;

@TableName("discovery")
public class DiscoveryDTO extends Model<DiscoveryDTO> implements Serializable {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activitiy_place
     *
     * @mbggenerated
     */
    private String activitiyPlace;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_organize
     *
     * @mbggenerated
     */
    private String activityOrganize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_contact
     *
     * @mbggenerated
     */
    private String activityContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy:MM:dd HH:mm:ss")
    private Date activityTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_content
     *
     * @mbggenerated
     */
    private String activityContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.publish_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy:MM:dd HH:mm:ss")
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.receiver_name
     *
     * @mbggenerated
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.receiver_type
     *
     * @mbggenerated
     */
    private String receiverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.receiver_phone
     *
     * @mbggenerated
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.receiver_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy:MM:dd HH:mm:ss")
    private Date receiverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.receiver_partner
     *
     * @mbggenerated
     */
    private String receiverPartner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.receiver_management
     *
     * @mbggenerated
     */
    private String receiverManagement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_topic
     *
     * @mbggenerated
     */
    private String activityTopic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_image1
     *
     * @mbggenerated
     */
    private String activityImage1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_image2
     *
     * @mbggenerated
     */
    private String activityImage2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_image3
     *
     * @mbggenerated
     */
    private String activityImage3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_text1
     *
     * @mbggenerated
     */
    private String activityText1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_text2
     *
     * @mbggenerated
     */
    private String activityText2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.over_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy:MM:dd HH:mm:ss")
    private Date overTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.finish_time
     *
     * @mbggenerated
     */
    @JSONField(format = "yyyy:MM:dd HH:mm:ss")
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_text3
     *
     * @mbggenerated
     */
    private String activityText3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.activity_comment
     *
     * @mbggenerated
     */
    private String activityComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.isReceived
     *
     * @mbggenerated
     */
    private Boolean isreceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.isFinished
     *
     * @mbggenerated
     */
    private Boolean isfinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discovery.isEnd
     *
     * @mbggenerated
     */

    private Boolean isover;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discovery
     *
     * @mbggenerated
     */
    public DiscoveryDTO(String id, String activitiyPlace, String activityOrganize, String activityContact, Date activityTime, String activityContent, Date publishTime, String receiverName, String receiverType, String receiverPhone, Date receiverTime, String receiverPartner, String receiverManagement, String activityTopic, String activityImage1, String activityImage2, String activityImage3, String activityText1, String activityText2, Date overTime, Date finishTime, String activityText3, String activityComment, Boolean isreceived, Boolean isfinished, Boolean isend, Boolean isover) {
        this.id = id;
        this.activitiyPlace = activitiyPlace;
        this.activityOrganize = activityOrganize;
        this.activityContact = activityContact;
        this.activityTime = activityTime;
        this.activityContent = activityContent;
        this.publishTime = publishTime;
        this.receiverName = receiverName;
        this.receiverType = receiverType;
        this.receiverPhone = receiverPhone;
        this.receiverTime = receiverTime;
        this.receiverPartner = receiverPartner;
        this.receiverManagement = receiverManagement;
        this.activityTopic = activityTopic;
        this.activityImage1 = activityImage1;
        this.activityImage2 = activityImage2;
        this.activityImage3 = activityImage3;
        this.activityText1 = activityText1;
        this.activityText2 = activityText2;
        this.overTime = overTime;
        this.finishTime = finishTime;
        this.activityText3 = activityText3;
        this.activityComment = activityComment;
        this.isreceived = isreceived;
        this.isfinished = isfinished;
        this.isover = isover;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getActivitiyPlace() {
        return activitiyPlace;
    }

    public void setActivitiyPlace(String activitiyPlace) {
        this.activitiyPlace = activitiyPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discovery
     *
     * @mbggenerated
     */
    public DiscoveryDTO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_organize
     *
     * @return the value of discovery.activity_organize
     * @mbggenerated
     */
    public String getActivityOrganize() {
        return activityOrganize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_organize
     *
     * @param activityOrganize the value for discovery.activity_organize
     * @mbggenerated
     */
    public void setActivityOrganize(String activityOrganize) {
        this.activityOrganize = activityOrganize == null ? null : activityOrganize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_contact
     *
     * @return the value of discovery.activity_contact
     * @mbggenerated
     */
    public String getActivityContact() {
        return activityContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_contact
     *
     * @param activityContact the value for discovery.activity_contact
     * @mbggenerated
     */
    public void setActivityContact(String activityContact) {
        this.activityContact = activityContact == null ? null : activityContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_time
     *
     * @return the value of discovery.activity_time
     * @mbggenerated
     */
    public Date getActivityTime() {
        return activityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_time
     *
     * @param activityTime the value for discovery.activity_time
     * @mbggenerated
     */
    public void setActivityTime(Date activityTime) {
        this.activityTime = activityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_content
     *
     * @return the value of discovery.activity_content
     * @mbggenerated
     */
    public String getActivityContent() {
        return activityContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_content
     *
     * @param activityContent the value for discovery.activity_content
     * @mbggenerated
     */
    public void setActivityContent(String activityContent) {
        this.activityContent = activityContent == null ? null : activityContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.publish_time
     *
     * @return the value of discovery.publish_time
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.publish_time
     *
     * @param publishTime the value for discovery.publish_time
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.receiver_name
     *
     * @return the value of discovery.receiver_name
     * @mbggenerated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.receiver_name
     *
     * @param receiverName the value for discovery.receiver_name
     * @mbggenerated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.receiver_type
     *
     * @return the value of discovery.receiver_type
     * @mbggenerated
     */
    public String getReceiverType() {
        return receiverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.receiver_type
     *
     * @param receiverType the value for discovery.receiver_type
     * @mbggenerated
     */
    public void setReceiverType(String receiverType) {
        this.receiverType = receiverType == null ? null : receiverType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.receiver_phone
     *
     * @return the value of discovery.receiver_phone
     * @mbggenerated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.receiver_phone
     *
     * @param receiverPhone the value for discovery.receiver_phone
     * @mbggenerated
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.receiver_time
     *
     * @return the value of discovery.receiver_time
     * @mbggenerated
     */
    public Date getReceiverTime() {
        return receiverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.receiver_time
     *
     * @param receiverTime the value for discovery.receiver_time
     * @mbggenerated
     */
    public void setReceiverTime(Date receiverTime) {
        this.receiverTime = receiverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.receiver_partner
     *
     * @return the value of discovery.receiver_partner
     * @mbggenerated
     */
    public String getReceiverPartner() {
        return receiverPartner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.receiver_partner
     *
     * @param receiverPartner the value for discovery.receiver_partner
     * @mbggenerated
     */
    public void setReceiverPartner(String receiverPartner) {
        this.receiverPartner = receiverPartner == null ? null : receiverPartner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.receiver_management
     *
     * @return the value of discovery.receiver_management
     * @mbggenerated
     */
    public String getReceiverManagement() {
        return receiverManagement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.receiver_management
     *
     * @param receiverManagement the value for discovery.receiver_management
     * @mbggenerated
     */
    public void setReceiverManagement(String receiverManagement) {
        this.receiverManagement = receiverManagement == null ? null : receiverManagement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_topic
     *
     * @return the value of discovery.activity_topic
     * @mbggenerated
     */
    public String getActivityTopic() {
        return activityTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_topic
     *
     * @param activityTopic the value for discovery.activity_topic
     * @mbggenerated
     */
    public void setActivityTopic(String activityTopic) {
        this.activityTopic = activityTopic == null ? null : activityTopic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_image1
     *
     * @return the value of discovery.activity_image1
     * @mbggenerated
     */
    public String getActivityImage1() {
        return activityImage1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_image1
     *
     * @param activityImage1 the value for discovery.activity_image1
     * @mbggenerated
     */
    public void setActivityImage1(String activityImage1) {
        this.activityImage1 = activityImage1 == null ? null : activityImage1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_image2
     *
     * @return the value of discovery.activity_image2
     * @mbggenerated
     */
    public String getActivityImage2() {
        return activityImage2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_image2
     *
     * @param activityImage2 the value for discovery.activity_image2
     * @mbggenerated
     */
    public void setActivityImage2(String activityImage2) {
        this.activityImage2 = activityImage2 == null ? null : activityImage2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_image3
     *
     * @return the value of discovery.activity_image3
     * @mbggenerated
     */
    public String getActivityImage3() {
        return activityImage3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_image3
     *
     * @param activityImage3 the value for discovery.activity_image3
     * @mbggenerated
     */
    public void setActivityImage3(String activityImage3) {
        this.activityImage3 = activityImage3 == null ? null : activityImage3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_text1
     *
     * @return the value of discovery.activity_text1
     * @mbggenerated
     */
    public String getActivityText1() {
        return activityText1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_text1
     *
     * @param activityText1 the value for discovery.activity_text1
     * @mbggenerated
     */
    public void setActivityText1(String activityText1) {
        this.activityText1 = activityText1 == null ? null : activityText1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_text2
     *
     * @return the value of discovery.activity_text2
     * @mbggenerated
     */
    public String getActivityText2() {
        return activityText2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_text2
     *
     * @param activityText2 the value for discovery.activity_text2
     * @mbggenerated
     */
    public void setActivityText2(String activityText2) {
        this.activityText2 = activityText2 == null ? null : activityText2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.over_time
     *
     * @return the value of discovery.over_time
     * @mbggenerated
     */
    public Date getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.over_time
     *
     * @param overTime the value for discovery.over_time
     * @mbggenerated
     */
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.finish_time
     *
     * @return the value of discovery.finish_time
     * @mbggenerated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.finish_time
     *
     * @param finishTime the value for discovery.finish_time
     * @mbggenerated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_text3
     *
     * @return the value of discovery.activity_text3
     * @mbggenerated
     */
    public String getActivityText3() {
        return activityText3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_text3
     *
     * @param activityText3 the value for discovery.activity_text3
     * @mbggenerated
     */
    public void setActivityText3(String activityText3) {
        this.activityText3 = activityText3 == null ? null : activityText3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.activity_comment
     *
     * @return the value of discovery.activity_comment
     * @mbggenerated
     */
    public String getActivityComment() {
        return activityComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.activity_comment
     *
     * @param activityComment the value for discovery.activity_comment
     * @mbggenerated
     */
    public void setActivityComment(String activityComment) {
        this.activityComment = activityComment == null ? null : activityComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.isReceived
     *
     * @return the value of discovery.isReceived
     * @mbggenerated
     */
    public Boolean getIsreceived() {
        return isreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.isReceived
     *
     * @param isreceived the value for discovery.isReceived
     * @mbggenerated
     */
    public void setIsreceived(Boolean isreceived) {
        this.isreceived = isreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discovery.isFinished
     *
     * @return the value of discovery.isFinished
     * @mbggenerated
     */
    public Boolean getIsfinished() {
        return isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discovery.isFinished
     *
     * @param isfinished the value for discovery.isFinished
     * @mbggenerated
     */
    public void setIsfinished(Boolean isfinished) {
        this.isfinished = isfinished;
    }

    public Boolean getIsOver() {
        return isover;
    }

    public void setIsOver(Boolean isover) {
        isover = isover;
    }

    @Override
    protected Serializable pkVal() {
        return null;
    }

    @Override
    public String toString() {
        return "DiscoveryDTO{" +
                "id='" + id + '\'' +
                ", activitiyPlace='" + activitiyPlace + '\'' +
                ", activityOrganize='" + activityOrganize + '\'' +
                ", activityContact='" + activityContact + '\'' +
                ", activityTime=" + activityTime +
                ", activityContent='" + activityContent + '\'' +
                ", publishTime=" + publishTime +
                ", receiverName='" + receiverName + '\'' +
                ", receiverType='" + receiverType + '\'' +
                ", receiverPhone='" + receiverPhone + '\'' +
                ", receiverTime=" + receiverTime +
                ", receiverPartner='" + receiverPartner + '\'' +
                ", receiverManagement='" + receiverManagement + '\'' +
                ", activityTopic='" + activityTopic + '\'' +
                ", activityImage1='" + activityImage1 + '\'' +
                ", activityImage2='" + activityImage2 + '\'' +
                ", activityImage3='" + activityImage3 + '\'' +
                ", activityText1='" + activityText1 + '\'' +
                ", activityText2='" + activityText2 + '\'' +
                ", overTime=" + overTime +
                ", finishTime=" + finishTime +
                ", activityText3='" + activityText3 + '\'' +
                ", activityComment='" + activityComment + '\'' +
                ", isreceived=" + isreceived +
                ", isfinished=" + isfinished +
                ", isover=" + isover +
                '}';
    }
}